// <auto-generated />
using ExcelCableGeneratorApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelCableGeneratorApp.Migrations
{
    [DbContext(typeof(CableJobContext))]
    [Migration("20240422022624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ExcelCableGeneratorApp.Persistence.Entity.Cable", b =>
                {
                    b.Property<int>("CableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AboveFinFloorLvl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CableType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PanelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuantityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StageCraftCableId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CableId");

                    b.HasIndex("JobId");

                    b.ToTable("Cables");
                });

            modelBuilder.Entity("ExcelCableGeneratorApp.Persistence.Entity.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ExcelCableGeneratorApp.Persistence.Entity.Cable", b =>
                {
                    b.HasOne("ExcelCableGeneratorApp.Persistence.Entity.Job", "Job")
                        .WithMany("Cables")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ExcelCableGeneratorApp.Persistence.Entity.Job", b =>
                {
                    b.Navigation("Cables");
                });
#pragma warning restore 612, 618
        }
    }
}
